# Generated by Django 4.0.5 on 2022-06-07 18:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='My Bio', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dcfb3gqzg/image/upload/v1654542339/bclz5p1q2ch81qz9ukpz.jpg', max_length=255, verbose_name='images'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('image_name', models.CharField(blank=True, max_length=50)),
                ('image_caption', models.TextField(blank=True, max_length=255)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='insta.profile')),
                ('image_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insta.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='insta.profile')),
            ],
        ),
    ]
