# Generated by Django 4.0.5 on 2022-06-06 08:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_images'),
        ),
    ]
